### PR TITLE
update to mob head drops

### PR DESCRIPTION
**Pull request by ardentcrest**
I believe this folder and files are also needed for the head drops is also

### CODE REVIEW

**Comment by Xeyame** [comment]
i don't think data/vanilla is used for anything, maybe look into cccc7af90dd00dbf2de19afb4c9ce555f9bc8668 how it was done there

**Comment by ardentcrest** [comment]
I have looked at other main 1.14 head drop datapacks all have a data/vanilla or data/(different name) folder and files.

**Comment by ardentcrest** [comment]
I could edit the files so it would all go into the proxus folder and not the vanilla one. but that is over 80 files to edit

**Comment by ardentcrest** [comment]
all 1.14 mob head datapacks  are using the two folders. If you could please add it to the server so we could test it to see if it works.

**Comment by Xeyame** [comment]
Can't you test them in single player?

**Comment by Xeyame** [comment]
And what about this file? 6b164ebfb8c70454bf166d4a9bfe57f0739527bd

**Comment by ardentcrest** [comment]
I should not think we need it as this does not show up in any other head pack

**Comment by Xeyame** [comment]
Ok, could you test it in single player?

**Comment by ardentcrest** [comment]
Works only as a zip file in the datapack folder. dose not work as separate folders

**Comment by Xeyame** [comment]
Yeah it's used and designed as a zip anyways, so mob heads work with this commit?

**Comment by ardentcrest** [comment]
tested. it works for me in single player

**Comment by Xeyame** [comment]
Thanks, can't add to server now (vacation) but already merging it. 🎉

**Pull request merged**
